package com.hassmedia.entity.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hassmedia.entity.HomeChannelBean;
import com.hassmedia.entity.HomeMenuBean;
import com.hassmedia.entity.HomeUiBean;
import com.hassmedia.entity.MovieSimpleBean;
import com.hassmedia.entity.UserEntity;

import com.hassmedia.entity.greendao.HomeChannelBeanDao;
import com.hassmedia.entity.greendao.HomeMenuBeanDao;
import com.hassmedia.entity.greendao.HomeUiBeanDao;
import com.hassmedia.entity.greendao.MovieSimpleBeanDao;
import com.hassmedia.entity.greendao.UserEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeChannelBeanDaoConfig;
    private final DaoConfig homeMenuBeanDaoConfig;
    private final DaoConfig homeUiBeanDaoConfig;
    private final DaoConfig movieSimpleBeanDaoConfig;
    private final DaoConfig userEntityDaoConfig;

    private final HomeChannelBeanDao homeChannelBeanDao;
    private final HomeMenuBeanDao homeMenuBeanDao;
    private final HomeUiBeanDao homeUiBeanDao;
    private final MovieSimpleBeanDao movieSimpleBeanDao;
    private final UserEntityDao userEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeChannelBeanDaoConfig = daoConfigMap.get(HomeChannelBeanDao.class).clone();
        homeChannelBeanDaoConfig.initIdentityScope(type);

        homeMenuBeanDaoConfig = daoConfigMap.get(HomeMenuBeanDao.class).clone();
        homeMenuBeanDaoConfig.initIdentityScope(type);

        homeUiBeanDaoConfig = daoConfigMap.get(HomeUiBeanDao.class).clone();
        homeUiBeanDaoConfig.initIdentityScope(type);

        movieSimpleBeanDaoConfig = daoConfigMap.get(MovieSimpleBeanDao.class).clone();
        movieSimpleBeanDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        homeChannelBeanDao = new HomeChannelBeanDao(homeChannelBeanDaoConfig, this);
        homeMenuBeanDao = new HomeMenuBeanDao(homeMenuBeanDaoConfig, this);
        homeUiBeanDao = new HomeUiBeanDao(homeUiBeanDaoConfig, this);
        movieSimpleBeanDao = new MovieSimpleBeanDao(movieSimpleBeanDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);

        registerDao(HomeChannelBean.class, homeChannelBeanDao);
        registerDao(HomeMenuBean.class, homeMenuBeanDao);
        registerDao(HomeUiBean.class, homeUiBeanDao);
        registerDao(MovieSimpleBean.class, movieSimpleBeanDao);
        registerDao(UserEntity.class, userEntityDao);
    }
    
    public void clear() {
        homeChannelBeanDaoConfig.clearIdentityScope();
        homeMenuBeanDaoConfig.clearIdentityScope();
        homeUiBeanDaoConfig.clearIdentityScope();
        movieSimpleBeanDaoConfig.clearIdentityScope();
        userEntityDaoConfig.clearIdentityScope();
    }

    public HomeChannelBeanDao getHomeChannelBeanDao() {
        return homeChannelBeanDao;
    }

    public HomeMenuBeanDao getHomeMenuBeanDao() {
        return homeMenuBeanDao;
    }

    public HomeUiBeanDao getHomeUiBeanDao() {
        return homeUiBeanDao;
    }

    public MovieSimpleBeanDao getMovieSimpleBeanDao() {
        return movieSimpleBeanDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

}
