package com.hassmedia.entity.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hassmedia.entity.HomeMenuBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOME_MENU_BEAN".
*/
public class HomeMenuBeanDao extends AbstractDao<HomeMenuBean, Long> {

    public static final String TABLENAME = "HOME_MENU_BEAN";

    /**
     * Properties of entity HomeMenuBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ApkPackage = new Property(1, String.class, "apkPackage", false, "APK_PACKAGE");
        public final static Property Url = new Property(2, String.class, "url", false, "URL");
        public final static Property UrlActive = new Property(3, String.class, "urlActive", false, "URL_ACTIVE");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property MenuCode = new Property(5, String.class, "menuCode", false, "MENU_CODE");
    }


    public HomeMenuBeanDao(DaoConfig config) {
        super(config);
    }
    
    public HomeMenuBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOME_MENU_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"APK_PACKAGE\" TEXT," + // 1: apkPackage
                "\"URL\" TEXT," + // 2: url
                "\"URL_ACTIVE\" TEXT," + // 3: urlActive
                "\"NAME\" TEXT," + // 4: name
                "\"MENU_CODE\" TEXT);"); // 5: menuCode
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOME_MENU_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HomeMenuBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String apkPackage = entity.getApkPackage();
        if (apkPackage != null) {
            stmt.bindString(2, apkPackage);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(3, url);
        }
 
        String urlActive = entity.getUrlActive();
        if (urlActive != null) {
            stmt.bindString(4, urlActive);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String menuCode = entity.getMenuCode();
        if (menuCode != null) {
            stmt.bindString(6, menuCode);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HomeMenuBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String apkPackage = entity.getApkPackage();
        if (apkPackage != null) {
            stmt.bindString(2, apkPackage);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(3, url);
        }
 
        String urlActive = entity.getUrlActive();
        if (urlActive != null) {
            stmt.bindString(4, urlActive);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String menuCode = entity.getMenuCode();
        if (menuCode != null) {
            stmt.bindString(6, menuCode);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HomeMenuBean readEntity(Cursor cursor, int offset) {
        HomeMenuBean entity = new HomeMenuBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // apkPackage
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // url
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // urlActive
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // menuCode
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HomeMenuBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setApkPackage(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUrlActive(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMenuCode(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HomeMenuBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HomeMenuBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HomeMenuBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
